name: app_emagro
description: "Aplicación móvil para el sistema de gestión agrícola Emagro"
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # HTTP requests
  http: ^1.1.0

  # Localization
  flutter_localizations:
    sdk: flutter

  # Local storage
  shared_preferences: ^2.2.2

  # Date formatting
  # intl: ^0.19.0

  # UI
  cupertino_icons: ^1.0.2

  # PDF generation
  pdf: ^3.10.0
  printing: ^5.11.0
  path_provider: ^2.1.0
  open_filex: ^4.3.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  # Assets
  assets:
    - assets/images/logo_emagro.png
    - assets/images/Fondo.jpeg
    - assets/images/BannerEmagro.png
